### ISSUE TITLE
Add support to subscribe to Video Motion Detection events

### ISSUE THREAD

**Issue by hustcalm** [AxisCommunications/modbus-acap#18]
Can we have some code examples on how to subscribe to motion detection events similar to the snippet blow:
```
 ax_event_key_value_set_add_key_values(
        key_value_set,
        NULL,
        "topic0",
        "tnsaxis",
        "CameraApplicationPlatform",
        AX_VALUE_TYPE_STRING,
        "topic1",
        "tnsaxis",
        "ObjectAnalytics",
        AX_VALUE_TYPE_STRING,
        "topic2",
        "tnsaxis",
        subscriptionstr,
        AX_VALUE_TYPE_STRING,
        NULL);
```
The code above subscribes to ACAP app, Axis Object Analytics's scenario 1/2/n (depends on the input parameter), so we need to create the scenarios manually first, is this correct?

I didn't find any documentation/code to describe how we can subscribe to the events of the ACAP app (Video Motion Detection), really appreciate if you can provide some or add the in this repo, thanks!

**Comment by bsriramprasad** [comment]
For video motion specific event subscription, as you have rightly pointed out, similar topic subscription structure need to filled, prerequisite being the scene/profile is created (either from available GUI after application is started e.g. 
http://192.168.0.90/local/vmd/index.html# or via API that VMD provides) as the same gets referred in the event subscription.

![image](https://user-images.githubusercontent.com/1432443/184134379-017f2d35-075e-4970-8698-9ad3efe5342f.png)

All the functionality of the Video Motion Detection Application (ACAP) is exposed via API documented here https://www.axis.com/vapix-library/subjects/t10102231/section/t10093855/display

You can see the VMD event declaration example below 
- Ref: https://www.axis.com/vapix-library/subjects/t10102231/section/t10093855/display?section=t10093855-t10091217

The same gets programatically filled in the code structure for example 

> ax_event_key_value_set_add_key_values(
        key_value_set,
        NULL,
        "topic0",
        "tnsaxis",
        "CameraApplicationPlatform",
        AX_VALUE_TYPE_STRING,
        "topic1",
        "tnsaxis",
        "**VMD**",
        AX_VALUE_TYPE_STRING,
        "topic2",
        "tnsaxis",
        subscriptionstr,
        AX_VALUE_TYPE_STRING,
        NULL);

**Comment by hustcalm** [comment]
Hi @bsriramprasad, thanks for the reply.

Two follow up questions:
1. In the code example above, for "subscriptionstr", what should be put there? For AXIS Object Analytics, it is something like "Device1Scenario1". For VMD, is it the same thing? Or we need to use "Device1Profile1"?
2. Does this work with different versions of AXIS Video Motion Detection apps? I noticed VMD3 and VMD4 at least in the documentation, so want to make sure the code works with them all.

Thanks,
Lihang

**Comment by bsriramprasad** [comment]
Hi Lihang,

The 'Scenario1' in AOA or 'Profile1' from VMD are default names for the scenario you are setting up the event for, you can (change them from application configuration interface http://192.168.0.90/local/vmd/index.html# to whatever you want to configure and use the same string in the event subscription as shown below

![image](https://user-images.githubusercontent.com/1432443/184867879-1862d371-0452-44e5-bca9-48f95c01b1a2.png)

Regarding VMD versions, here is the recommendation Ref: https://www.axis.com/products/axis-video-motion-detection

> AXIS Video Motion Detection 4 is the latest version and is supported and preinstalled in all Axis video products with firmware 6.50.4 and higher. It is not possible to download the app separately. To reinstall your product’s firmware, please click [here](https://www.axis.com/support/firmware). 
>
> For Axis video products with firmware 5.60 to 6.50.2 please click [here](https://www.axis.com/products/axis-video-motion-detection-3/support) to download AXIS Video Motion Detection 3. For Axis video products with firmware version 5.40.x, please click [here ](https://www.axis.com/products/axis-video-motion-detection-2/support)to download AXIS Video Motion Detection 2.

**As you can see VMD3 is for quite older firmwares which is almost or nearing end of life (Ref: https://help.axis.com/sv-se/axis-os#lts-2016-6-50) , hence I would strongly recommend you to just work with VMD4 as that is supported on almost every Axis camera but can't say that for VMD3/2.**

Do let me know if you have any further queries.

**Comment by hustcalm** [comment]
Thanks Sriram for the detailed answer, it's really helpful. I've successfully subscribed to the VMD events within an ACAP app based on your instructions, really appreciate your help!
