### ISSUE TITLE
A digital output remains on for 6 seconds even though the detection is over

### ISSUE THREAD

**Issue by ODP9** [AxisCommunications/modbus-acap#32]
HI Everyone,

When i used the modbus-acap to turn on digital output in modbus TCP/IP with the AXIS camera M2035-LE, i have this problem:
When the camera detects motion, the output turns on almost simultaneously, but when the motion detection ends, the output remains on for another 6 seconds, it's happened in modbus emulation and in physical module.

Has anyone encountered this problem? And what could be the solution?

**Comment by joakimr-axis** [comment]
Thank you for reporting!
Is it after the AOA event that the motion is no longer active (which takes a couple of seconds to receive after there is no motion) that you get a 6 second delay, or is it perhaps this delay that we are seeing here?
The reason I ask is to figure out if there is a delay after we make the call to libmodbus, or if it is actually a delay from AOA making sure that the movement has actually stopped.

**Comment by ODP9** [comment]
Joakimr thank you for the response,

The delay is after the AOA event is finished, when the AOA event motion is no longer active, then it takes about 6 seconds to receive that the AOA event motion no longer active and then it get 0 signal to the modbus.(i have attched a video)

https://user-images.githubusercontent.com/127041211/233278082-79fc1797-d284-463e-a7f6-30cf9711d898.mp4

**Comment by joakimr-axis** [comment]
Excellent idea to report with the screen recording, thanks!
What I am thinking here is the next step is to find out when the event reaches the ACAP.
The callback function triggered when we get the event from the camera's event system is here:

https://github.com/AxisCommunications/modbus-acap/blob/main/modbusacap.c#L49-L66

and it will write to the log here:

https://github.com/AxisCommunications/modbus-acap/blob/main/modbusacap.c#L62

If you check the timestamp for when the log writes that the ACAP is notified that the event is no longer active and compare that to what you get on modbus, does the time from the ACAP align with the graphical representation in the UI or with the Ethernet I/O module?

**Comment by Mzajkhost** [comment]
Thanks for your response, the time align with time in UI and Modbus as it shows in logs 
Here is the log for two events sent to modbus

2023-04-21T02:46:10.292+03:00 axis-b8a44f489ae1 [ INFO    ] modbusacap[781530]: modbus_client.c/modbus_client_send_event: Successfully called modbus_write_bit
2023-04-21T02:46:16.178+03:00 axis-b8a44f489ae1 [ INFO    ] modbusacap[781530]: aoa-event NOT active
2023-04-21T02:46:16.178+03:00 axis-b8a44f489ae1 [ INFO    ] modbusacap[781530]: modbus_client.c/modbus_client_send_event_not: Successfully called modbus_write_bit
2023-04-21T02:47:33.797+03:00 axis-b8a44f489ae1 [ INFO    ] modbusacap[781530]: modbus_client.c/modbus_client_send_event: Successfully called modbus_write_bit
2023-04-21T02:47:40.187+03:00 axis-b8a44f489ae1 [ INFO    ] modbusacap[781530]: aoa-event NOT active
2023-04-21T02:47:40.196+03:00 axis-b8a44f489ae1 [ INFO    ] modbusacap[781530]: modbus_client.c/modbus_client_send_event_not: Successfully called modbus_write_bit

**Comment by joakimr-axis** [comment]
https://user-images.githubusercontent.com/47358365/233945203-1ae19d56-d9e7-46a9-9fe9-68997008043c.mp4

Please have a look at this screen recording. I am here running a setup with two devices, the ACAP running on each of them but one in client mode and one in server mode (the terminals to the right). When I click the _Test Alarm_ button in AOA, I see that the event instantly triggers the functionality in the ACAP. I also see that the event is instantly propagated over modbus.

Then, after ~6 seconds the alarm goes inative (this is just the test alarm, but had it been a real situation we would have e.g. a person in the scene who then left the scene and then after a timeout the alarm would go inactive) and instantly, the ACAP gets that event and propagates it over modbus, and we also see on the other device that it instantly gets the notification (over modbus) that the AOA alarm on the other device was again inactive.

To me, all this behaves as expected.

**Comment by Mzajkhost** [comment]
Thanks for your response 
The modbus receive the active status fine but on not active status there is delay
We tried it on test and on real case
And the detection delay around 6 seconds to get not active even in real detection

**Comment by joakimr-axis** [comment]
But you are not confusing the AOA timeout time window of ~6 seconds with delay in modbus now, right?
From what I can see, everything that is done in this repo's ACAP happens instantaneously.

**Comment by Mzajkhost** [comment]
Yes im not confusing between the delay time
I will try to record a real video from real case
To let you see the delay is exist on not active event
What we need to get not active status without 6 seconds delay that happened on test and real

**Comment by joakimr-axis** [comment]
But as you can see in my video, there is no delay from when the ACAP gets the not active event from AOA until it is propagated over modbus!

**Comment by Mzajkhost** [comment]
Yes but its not clear enough, as you can see the trigger from active till not active takes 6 seconds in your video
Can you use modbus slave and then you can it clearly
And try to detect object instead of test button

**Comment by ODP9** [comment]
> But as you can see in my video, there is no delay from when the ACAP gets the not active event from AOA until it is propagated over modbus!

Joakim Roubert,
 
Thank you for your serious willingness to solve the problem, 

Following on from everything we have seen, what could actually be the reason that the alarm detection via MODBUS at the beginning is immediate without any delay, but at the end of the alarm, the response from the MODBUS side is with a delay, even as you proved in the video there is none, what is the difference? what can cause it?

**Comment by joakimr-axis** [comment]
If the alarm would toggle between active and not active without any inertia, every movement in the scene would cause a torrent of alarm toggles. Hence there is a time out for the alarm, so when there is no longer movement of the object, the alarm will stay active for a few seconds (and if it is then new movement, that timer will be reset). If there still is no new movement after this time, the alarm status will go back to not active. This is the delay you see in my screen recording: When I click the "test alarm", it injects a fake movement that triggers the alarm. Then, since there are no more triggers coming, the alarm status will go back to not active after the timeout grace period.

You see this in the upper terminal, that receives the events from the camera's event system and passes them on via modbus. And as soon as they are passed on through modbus (upper terminal), they are also received over modbus (lower terminal).
